version: "2"
checks:
  complex-logic:
    config:
      threshold: 15
  method-complexity:
    config:
      threshold: 15

engines:
  gofmt:
    enabled: true
  golint:
    enabled: true
  govet:
    enabled: true
